name: Deploy GTS Frontend

on:
  push:
    branches:
      - main
      - homologation
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: gts-frontend
          environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
